"""
CW shell completion — generates completion scripts for bash, zsh, and fish.

The completion dynamically reads Context and Window names from
the SQLite database, so tab-completion always shows current data.

Usage:
    cw completion bash >> ~/.bashrc
    cw completion zsh  >> ~/.zshrc
    cw completion fish > ~/.config/fish/completions/cw.fish
"""

from __future__ import annotations


def generate_completion(shell: str) -> str:
    """
    Generate a shell completion script for the given shell.

    @param shell: One of "bash", "zsh", "fish".
    @returns: Complete shell script as a string.
    """
    generators = {
        "bash": _bash_completion,
        "zsh": _zsh_completion,
        "fish": _fish_completion,
    }
    generator = generators.get(shell)
    if not generator:
        raise ValueError(f"Unsupported shell: {shell}. Use bash, zsh, or fish.")
    return generator()


def _bash_completion() -> str:
    """Generate bash completion script."""
    return r'''# CW bash completion — add to ~/.bashrc or ~/.bash_completion
# Generated by: cw completion bash

_cw_completions() {
    local cur prev commands
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    commands="list create join leave open close save history status windows go rename reload backup config completion"

    # Complete subcommand
    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
        return
    fi

    # Determine which argument position we're completing
    local cmd="${COMP_WORDS[1]}"

    # Helper: fuzzy match (case-insensitive + latin→cyrillic transliteration)
    _cw_fuzzy_match() {
        local query="$1"
        shift
        python3 -c "
import sys
query = sys.argv[1]
candidates = sys.argv[2:]
# Latin → Cyrillic mapping (Serbian)
lat2cyr = {
    'a':'а','b':'б','v':'в','g':'г','d':'д','đ':'ђ','e':'е','ž':'ж',
    'z':'з','i':'и','j':'ј','k':'к','l':'л','lj':'љ','m':'м','n':'н',
    'nj':'њ','o':'о','p':'п','r':'р','s':'с','t':'т','ć':'ћ','u':'у',
    'f':'ф','h':'х','c':'ц','č':'ч','dž':'џ','š':'ш',
    'dj':'ђ','zh':'ж','nj':'њ','lj':'љ','dz':'џ',
}
def transliterate(text):
    result = ''
    i = 0
    t = text.lower()
    while i < len(t):
        if i+2 <= len(t) and t[i:i+2] in lat2cyr:
            result += lat2cyr[t[i:i+2]]
            i += 2
        elif t[i] in lat2cyr:
            result += lat2cyr[t[i]]
            i += 1
        else:
            result += t[i]
            i += 1
    return result
q_lower = query.lower()
q_cyr = transliterate(query)
for c in candidates:
    c_lower = c.lower()
    if c_lower.startswith(q_lower) or c_lower.startswith(q_cyr):
        print(c)
" "$query" "$@" 2>/dev/null
    }

    # Escape spaces in completion results so bash treats them as single args
    _cw_escape() {
        local i
        for i in "$@"; do
            printf '%s\n' "${i// /\\ }"
        done
    }

    if [ "$COMP_CWORD" -eq 2 ]; then
        # First argument after command — context names (or target for go/rename)
        case "$cmd" in
            open|close|save|history|join|leave|windows|rename)
                if [[ "$cur" == */* ]]; then
                    local ctx_name="${cur%%/*}"
                    local win_query="${cur#*/}"
                    local -a windows
                    mapfile -t windows < <(_cw_list_windows "$ctx_name" 2>/dev/null)
                    local -a matches
                    mapfile -t matches < <(_cw_fuzzy_match "$win_query" "${windows[@]}")
                    local -a escaped
                    mapfile -t escaped < <(_cw_escape "${matches[@]/#/${ctx_name}/}")
                    COMPREPLY=( "${escaped[@]}" )
                else
                    # Append / instead of space so user can continue to window name
                    compopt -o nospace
                    local -a contexts
                    mapfile -t contexts < <(_cw_list_contexts 2>/dev/null)
                    local -a matches
                    mapfile -t matches < <(_cw_fuzzy_match "$cur" "${contexts[@]}")
                    COMPREPLY=( "${matches[@]/%//}" )
                fi
                ;;
            go)
                if [[ "$cur" == */* ]]; then
                    local ctx_name="${cur%%/*}"
                    local win_query="${cur#*/}"
                    local -a windows
                    mapfile -t windows < <(_cw_list_windows "$ctx_name" 2>/dev/null)
                    local -a matches
                    mapfile -t matches < <(_cw_fuzzy_match "$win_query" "${windows[@]}")
                    local -a escaped
                    mapfile -t escaped < <(_cw_escape "${matches[@]/#/${ctx_name}/}")
                    COMPREPLY=( "${escaped[@]}" )
                else
                    compopt -o nospace
                    # Context names get / suffix, iTerm titles get space
                    local -a contexts ctx_matches
                    mapfile -t contexts < <(_cw_list_contexts 2>/dev/null)
                    mapfile -t ctx_matches < <(_cw_fuzzy_match "$cur" "${contexts[@]}")
                    local -a titles title_matches
                    mapfile -t titles < <(_cw_list_iterm_titles_all 2>/dev/null)
                    mapfile -t title_matches < <(_cw_fuzzy_match "$cur" "${titles[@]}")
                    # Context names with / suffix
                    COMPREPLY=( "${ctx_matches[@]/%//}" )
                    # iTerm titles with space suffix
                    local t
                    for t in "${title_matches[@]}"; do
                        [ -n "$t" ] && COMPREPLY+=( "$t " )
                    done
                fi
                ;;
            completion)
                COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") )
                ;;
        esac
    elif [ "$COMP_CWORD" -eq 3 ]; then
        # Second argument — depends on command
        case "$cmd" in
            join)
                # Complete iTerm window titles (untracked windows) with fuzzy match
                local -a titles matches
                mapfile -t titles < <(_cw_list_iterm_titles 2>/dev/null)
                mapfile -t matches < <(_cw_fuzzy_match "$cur" "${titles[@]}")
                local -a escaped
                mapfile -t escaped < <(_cw_escape "${matches[@]}")
                COMPREPLY=( "${escaped[@]}" )
                ;;
        esac
    fi
}

# Read iTerm window titles via daemon socket (for join completion)
_cw_list_iterm_titles() {
    python3 -c "
import socket, json
from cw.constants import SOCKET_PATH, SOCKET_BUFFER_SIZE
if SOCKET_PATH.exists():
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s.settimeout(2)
    try:
        s.connect(str(SOCKET_PATH))
        s.sendall(json.dumps({'cmd':'_complete_iterm_titles','args':{'filter':'untracked'}}).encode())
        data = b''
        while True:
            chunk = s.recv(SOCKET_BUFFER_SIZE)
            if not chunk: break
            data += chunk
        resp = json.loads(data)
        if resp.get('ok'):
            for t in resp['data']['titles']:
                print(t)
    except: pass
    finally: s.close()
" 2>/dev/null
}

# Read ALL iTerm window titles via daemon (for go completion)
_cw_list_iterm_titles_all() {
    python3 -c "
import socket, json
from cw.constants import SOCKET_PATH, SOCKET_BUFFER_SIZE
if SOCKET_PATH.exists():
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s.settimeout(2)
    try:
        s.connect(str(SOCKET_PATH))
        s.sendall(json.dumps({'cmd':'_complete_iterm_titles','args':{'filter':'all'}}).encode())
        data = b''
        while True:
            chunk = s.recv(SOCKET_BUFFER_SIZE)
            if not chunk: break
            data += chunk
        resp = json.loads(data)
        if resp.get('ok'):
            for t in resp['data']['titles']:
                print(t)
    except: pass
    finally: s.close()
" 2>/dev/null
}

# Read context names from CW database
_cw_list_contexts() {
    python3 -c "
from cw.db import CwDatabase
from cw.constants import DB_PATH
if DB_PATH.exists():
    db = CwDatabase()
    for c in db.list_contexts():
        print(c.name)
    db.close()
" 2>/dev/null
}

# Read window names for a specific context
_cw_list_windows() {
    local ctx_name="$1"
    python3 -c "
from cw.db import CwDatabase
from cw.constants import DB_PATH
if DB_PATH.exists():
    db = CwDatabase()
    ctx = db.get_context_by_name('$ctx_name')
    if ctx:
        for w in ctx.windows:
            if w.is_member:
                print(w.name)
    db.close()
" 2>/dev/null
}

complete -F _cw_completions cw
'''


def _zsh_completion() -> str:
    """Generate zsh completion script."""
    return r'''# CW zsh completion — add to ~/.zshrc
# Generated by: cw completion zsh

_cw() {
    local -a commands contexts

    commands=(
        'list:Show all Contexts with live status'
        'create:Create a new Context'
        'join:Add a window to a Context'
        'leave:Remove current window from Context'
        'open:Restore closed windows'
        'close:Save and close windows'
        'save:Force a snapshot'
        'history:Show state history'
        'status:Show daemon status'
        'windows:Show windows in a Context'
        'go:Jump to a Context window'
        'rename:Rename a Context or Window'
        'reload:Reload daemon code'
        'backup:Backup database'
        'config:View or update configuration'
        'completion:Output shell completion script'
    )

    if (( CURRENT == 2 )); then
        _describe 'command' commands
        return
    fi

    if (( CURRENT == 3 )); then
        case "${words[2]}" in
            open|close|save|history|join|windows|go|rename)
                if [[ "${words[CURRENT]}" == */* ]]; then
                    local ctx_name="${words[CURRENT]%%/*}"
                    local -a windows
                    windows=( $(_cw_list_windows "$ctx_name") )
                    _describe 'window' windows -P "${ctx_name}/"
                else
                    contexts=( $(_cw_list_contexts) )
                    compadd -S '/' -q -- "${contexts[@]}"
                fi
                ;;
            completion)
                _values 'shell' bash zsh fish
                ;;
        esac
    elif (( CURRENT == 4 )); then
        case "${words[2]}" in
            join)
                # Complete iTerm window titles for second arg
                local -a titles
                titles=( $(_cw_list_iterm_titles) )
                compadd -- "${titles[@]}"
                ;;
        esac
    fi
}

_cw_list_contexts() {
    python3 -c "
from cw.db import CwDatabase
from cw.constants import DB_PATH
if DB_PATH.exists():
    db = CwDatabase()
    for c in db.list_contexts():
        print(c.name)
    db.close()
" 2>/dev/null
}

_cw_list_windows() {
    local ctx_name="$1"
    python3 -c "
from cw.db import CwDatabase
from cw.constants import DB_PATH
if DB_PATH.exists():
    db = CwDatabase()
    ctx = db.get_context_by_name('$ctx_name')
    if ctx:
        for w in ctx.windows:
            if w.is_member:
                print(w.name)
    db.close()
" 2>/dev/null
}

_cw_list_iterm_titles() {
    python3 -c "
import socket, json
from cw.constants import SOCKET_PATH, SOCKET_BUFFER_SIZE
if SOCKET_PATH.exists():
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s.settimeout(2)
    try:
        s.connect(str(SOCKET_PATH))
        s.sendall(json.dumps({'cmd':'_complete_iterm_titles','args':{'filter':'untracked'}}).encode())
        data = b''
        while True:
            chunk = s.recv(SOCKET_BUFFER_SIZE)
            if not chunk: break
            data += chunk
        resp = json.loads(data)
        if resp.get('ok'):
            for t in resp['data']['titles']:
                print(t)
    except: pass
    finally: s.close()
" 2>/dev/null
}

compdef _cw cw
'''


def _fish_completion() -> str:
    """Generate fish completion script."""
    return r'''# CW fish completion — save to ~/.config/fish/completions/cw.fish
# Generated by: cw completion fish

# Subcommands
set -l cw_commands list create join leave open close save history status windows go rename reload backup config completion

# Disable file completions for cw
complete -c cw -f

# Subcommand completions
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "list" -d "Show all Contexts"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "create" -d "Create a new Context"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "join" -d "Add window to Context"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "leave" -d "Remove window from Context"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "open" -d "Restore closed windows"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "close" -d "Save and close windows"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "save" -d "Force a snapshot"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "history" -d "Show state history"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "status" -d "Show daemon status"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "windows" -d "Show windows in Context"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "go" -d "Jump to Context window"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "rename" -d "Rename Context or Window"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "reload" -d "Reload daemon code"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "backup" -d "Backup database"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "config" -d "View/update configuration"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "completion" -d "Output completion script"

# Context name completions for relevant subcommands
for cmd in open close save history join windows go rename
    complete -c cw -n "__fish_seen_subcommand_from $cmd" -a "(python3 -c '
from cw.db import CwDatabase
from cw.constants import DB_PATH
if DB_PATH.exists():
    db = CwDatabase()
    for c in db.list_contexts():
        print(c.name)
    db.close()
' 2>/dev/null)"
end

# Shell completions for completion subcommand
complete -c cw -n "__fish_seen_subcommand_from completion" -a "bash zsh fish"
'''
