"""
CW shell completion — generates completion scripts for bash, zsh, and fish.

The completion dynamically reads Context and Window names from
the SQLite database, so tab-completion always shows current data.

Usage:
    cw completion bash >> ~/.bashrc
    cw completion zsh  >> ~/.zshrc
    cw completion fish > ~/.config/fish/completions/cw.fish
"""

from __future__ import annotations


def generate_completion(shell: str) -> str:
    """
    Generate a shell completion script for the given shell.

    @param shell: One of "bash", "zsh", "fish".
    @returns: Complete shell script as a string.
    """
    generators = {
        "bash": _bash_completion,
        "zsh": _zsh_completion,
        "fish": _fish_completion,
    }
    generator = generators.get(shell)
    if not generator:
        raise ValueError(f"Unsupported shell: {shell}. Use bash, zsh, or fish.")
    return generator()


def _bash_completion() -> str:
    """Generate bash completion script."""
    return r'''# CW bash completion — add to ~/.bashrc or ~/.bash_completion
# Generated by: cw completion bash

_cw_completions() {
    local cur prev commands
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    commands="list create join open close save history status windows completion"

    # Complete subcommand
    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
        return
    fi

    # Complete context names for commands that need them
    case "$prev" in
        open|close|save|history|join|windows)
            local contexts
            contexts=$(_cw_list_contexts 2>/dev/null)
            # Support Context/Window completion
            if [[ "$cur" == */* ]]; then
                local ctx_name="${cur%%/*}"
                local windows
                windows=$(_cw_list_windows "$ctx_name" 2>/dev/null)
                COMPREPLY=( $(compgen -P "${ctx_name}/" -W "$windows" -- "${cur#*/}") )
            else
                COMPREPLY=( $(compgen -W "$contexts" -- "$cur") )
            fi
            ;;
        completion)
            COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") )
            ;;
    esac
}

# Read context names from CW database
_cw_list_contexts() {
    python3 -c "
from cw.db import CwDatabase
from cw.constants import DB_PATH
if DB_PATH.exists():
    db = CwDatabase()
    for c in db.list_contexts():
        print(c.name)
    db.close()
" 2>/dev/null
}

# Read window names for a specific context
_cw_list_windows() {
    local ctx_name="$1"
    python3 -c "
from cw.db import CwDatabase
from cw.constants import DB_PATH
if DB_PATH.exists():
    db = CwDatabase()
    ctx = db.get_context_by_name('$ctx_name')
    if ctx:
        for w in ctx.windows:
            if w.is_member:
                print(w.name)
    db.close()
" 2>/dev/null
}

complete -F _cw_completions cw
'''


def _zsh_completion() -> str:
    """Generate zsh completion script."""
    return r'''# CW zsh completion — add to ~/.zshrc
# Generated by: cw completion zsh

_cw() {
    local -a commands contexts

    commands=(
        'list:Show all Contexts with live status'
        'create:Create a new Context'
        'join:Add current window to a Context'
        'open:Restore closed windows'
        'close:Save and close windows'
        'save:Force a snapshot'
        'history:Show state history'
        'status:Show daemon status'
        'windows:Show windows in a Context'
        'completion:Output shell completion script'
    )

    if (( CURRENT == 2 )); then
        _describe 'command' commands
        return
    fi

    case "${words[2]}" in
        open|close|save|history|join|windows)
            # Complete context names, support Context/Window
            if [[ "${words[CURRENT]}" == */* ]]; then
                local ctx_name="${words[CURRENT]%%/*}"
                local -a windows
                windows=( $(_cw_list_windows "$ctx_name") )
                _describe 'window' windows -P "${ctx_name}/"
            else
                contexts=( $(_cw_list_contexts) )
                # Add trailing / to suggest further completion
                compadd -S '/' -q -- "${contexts[@]}"
            fi
            ;;
        completion)
            _values 'shell' bash zsh fish
            ;;
    esac
}

_cw_list_contexts() {
    python3 -c "
from cw.db import CwDatabase
from cw.constants import DB_PATH
if DB_PATH.exists():
    db = CwDatabase()
    for c in db.list_contexts():
        print(c.name)
    db.close()
" 2>/dev/null
}

_cw_list_windows() {
    local ctx_name="$1"
    python3 -c "
from cw.db import CwDatabase
from cw.constants import DB_PATH
if DB_PATH.exists():
    db = CwDatabase()
    ctx = db.get_context_by_name('$ctx_name')
    if ctx:
        for w in ctx.windows:
            if w.is_member:
                print(w.name)
    db.close()
" 2>/dev/null
}

compdef _cw cw
'''


def _fish_completion() -> str:
    """Generate fish completion script."""
    return r'''# CW fish completion — save to ~/.config/fish/completions/cw.fish
# Generated by: cw completion fish

# Subcommands
set -l cw_commands list create join open close save history status windows completion

# Disable file completions for cw
complete -c cw -f

# Subcommand completions
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "list" -d "Show all Contexts"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "create" -d "Create a new Context"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "join" -d "Add window to Context"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "open" -d "Restore closed windows"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "close" -d "Save and close windows"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "save" -d "Force a snapshot"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "history" -d "Show state history"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "status" -d "Show daemon status"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "windows" -d "Show windows in Context"
complete -c cw -n "not __fish_seen_subcommand_from $cw_commands" -a "completion" -d "Output completion script"

# Context name completions for relevant subcommands
for cmd in open close save history join windows
    complete -c cw -n "__fish_seen_subcommand_from $cmd" -a "(python3 -c '
from cw.db import CwDatabase
from cw.constants import DB_PATH
if DB_PATH.exists():
    db = CwDatabase()
    for c in db.list_contexts():
        print(c.name)
    db.close()
' 2>/dev/null)"
end

# Shell completions for completion subcommand
complete -c cw -n "__fish_seen_subcommand_from completion" -a "bash zsh fish"
'''
