#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────
# CW Install Script — full installation of Contextual-Walker.
#
# What this script does:
#   1. Creates Python virtual environment (.venv)
#   2. Installs CW package + dependencies (pip install -e .)
#   3. Creates ~/.contextual-walker/ directory
#   4. Initializes the SQLite database
#   5. Installs daemon into iTerm2 AutoLaunch
#   6. Generates and installs man pages
#   7. Detects user's shell and installs completion
#
# Usage:
#   bash scripts/install.sh [--backup-dir /path/to/backups]
#
# After running:
#   - Restart iTerm2 (daemon will auto-start)
#   - Open a new shell (for completion to load)
# ──────────────────────────────────────────────────────────────────

set -euo pipefail

# Parse optional --backup-dir argument
CUSTOM_BACKUP_DIR=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --backup-dir)
            CUSTOM_BACKUP_DIR="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: bash scripts/install.sh [--backup-dir /path/to/backups]"
            exit 1
            ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
VENV_DIR="$PROJECT_DIR/.venv"
CW_HOME="$HOME/.contextual-walker"
ITERM_AUTOLAUNCH="$HOME/Library/Application Support/iTerm2/Scripts/AutoLaunch"
DAEMON_SOURCE="$PROJECT_DIR/src/cw/daemon.py"

echo "╔══════════════════════════════════════════════════╗"
echo "║       Contextual-Walker — Installation           ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""

# ─── Find best Python ─────────────────────────────────────────────
# Prefer Homebrew Python 3.13+, fall back to system python3
PYTHON=""
for candidate in /opt/homebrew/bin/python3.14 /opt/homebrew/bin/python3.13 /opt/homebrew/bin/python3.12 /opt/homebrew/bin/python3 python3; do
    if command -v "$candidate" &>/dev/null; then
        version=$("$candidate" --version 2>&1 | grep -oE '[0-9]+\.[0-9]+')
        major=$(echo "$version" | cut -d. -f1)
        minor=$(echo "$version" | cut -d. -f2)
        if [ "$major" -ge 3 ] && [ "$minor" -ge 10 ]; then
            PYTHON="$candidate"
            break
        fi
    fi
done

if [ -z "$PYTHON" ]; then
    echo "ERROR: Python 3.10+ is required but not found."
    echo "Install with: brew install python@3.13"
    exit 1
fi

echo "→ Using Python: $PYTHON ($($PYTHON --version))"

# ─── Step 1: Virtual environment ──────────────────────────────────
echo ""
echo "→ Step 1/7: Setting up virtual environment ..."
if [ -d "$VENV_DIR" ]; then
    echo "  ✓ .venv already exists"
else
    "$PYTHON" -m venv "$VENV_DIR"
    echo "  ✓ .venv created"
fi

# Activate venv for the rest of the script
source "$VENV_DIR/bin/activate"

# ─── Step 2: Install CW package ──────────────────────────────────
echo ""
echo "→ Step 2/7: Installing CW package ..."
pip install --quiet -e "$PROJECT_DIR"
echo "  ✓ CW installed ($(cw --version 2>&1))"

# ─── Step 3: Create CW home directory ─────────────────────────────
echo ""
echo "→ Step 3/7: Creating $CW_HOME ..."
mkdir -p "$CW_HOME"
echo "  ✓ Directory ready"

# ─── Step 4: Initialize database ──────────────────────────────────
echo ""
echo "→ Step 4/7: Initializing database ..."
python3 -c "
from cw.db import CwDatabase
db = CwDatabase()
db.init_schema()
print('  ✓ Database initialized at', db.db_path)
db.close()
"

# ─── Step 5: Install daemon to iTerm2 AutoLaunch ──────────────────
echo ""
echo "→ Step 5/7: Installing daemon to iTerm2 ..."
mkdir -p "$ITERM_AUTOLAUNCH"

DAEMON_WRAPPER="$ITERM_AUTOLAUNCH/cw_daemon.py"

cat > "$DAEMON_WRAPPER" << WRAPPER_EOF
#!/usr/bin/env python3
"""
CW Daemon — iTerm2 AutoLaunch wrapper.

Auto-generated by install.sh — do not edit manually.
Source: $DAEMON_SOURCE
"""
import sys
sys.path.insert(0, "$PROJECT_DIR/src")

from cw.daemon import main
import iterm2
iterm2.run_forever(main)
WRAPPER_EOF

chmod +x "$DAEMON_WRAPPER"
echo "  ✓ Daemon installed at: $DAEMON_WRAPPER"

# ─── Step 6: Make `cw` available system-wide ─────────────────────
echo ""
echo "→ Step 6/9: Making 'cw' available in PATH ..."
CW_BIN="$VENV_DIR/bin/cw"
SYMLINK_TARGET="/usr/local/bin/cw"

if [ -L "$SYMLINK_TARGET" ] || [ -f "$SYMLINK_TARGET" ]; then
    # Already exists — update it
    if [ -L "$SYMLINK_TARGET" ]; then
        rm "$SYMLINK_TARGET"
    fi
fi

if ln -s "$CW_BIN" "$SYMLINK_TARGET" 2>/dev/null; then
    echo "  ✓ Symlink created: $SYMLINK_TARGET → $CW_BIN"
else
    # No write access to /usr/local/bin — fall back to shell config PATH
    echo "  ⚠ Cannot write to $SYMLINK_TARGET (no sudo)"
    echo "    Adding PATH to shell config instead ..."
    CW_PATH_LINE="export PATH=\"$VENV_DIR/bin:\$PATH\"  # CW (Contextual-Walker)"
    # Add PATH to ALL rc files that exist, so it works regardless
    # of which shell the user actually runs (bash, zsh, etc.)
    PATH_ADDED=false
    for RC_FILE in "$HOME/.bashrc" "$HOME/.zshrc"; do
        if [ -f "$RC_FILE" ]; then
            if ! grep -q "# CW (Contextual-Walker)" "$RC_FILE" 2>/dev/null; then
                # Insert PATH at the TOP of the file (before any completion that needs it)
                TEMP_RC=$(mktemp)
                echo "$CW_PATH_LINE" > "$TEMP_RC"
                echo "" >> "$TEMP_RC"
                cat "$RC_FILE" >> "$TEMP_RC"
                mv "$TEMP_RC" "$RC_FILE"
                echo "  ✓ PATH added to $RC_FILE (at top)"
            else
                echo "  ✓ PATH already in $RC_FILE"
            fi
            PATH_ADDED=true
        fi
    done
    if [ "$PATH_ADDED" = false ]; then
        # No rc files found — create .bashrc
        echo "$CW_PATH_LINE" > "$HOME/.bashrc"
        echo "  ✓ PATH added to ~/.bashrc (created)"
    fi
fi

# ─── Step 7: Man pages ────────────────────────────────────────────
echo ""
echo "→ Step 7/9: Generating man pages ..."
MAN_DIR="$PROJECT_DIR/man"
LOCAL_MAN="$HOME/.local/share/man/man1"
mkdir -p "$MAN_DIR" "$LOCAL_MAN"

if command -v help2man &>/dev/null; then
    # Generate main man page
    help2man --no-info --name="persistent context manager for iTerm2" cw > "$MAN_DIR/cw.1" 2>/dev/null || true
    # Generate per-subcommand man pages
    for subcmd in list create join open close save history windows status backup config completion; do
        help2man --no-info --name="cw $subcmd" "cw $subcmd" > "$MAN_DIR/cw-$subcmd.1" 2>/dev/null || true
    done
    # Install to user-local man path (no sudo needed)
    cp "$MAN_DIR"/cw*.1 "$LOCAL_MAN/" 2>/dev/null || true

    # Add MANPATH to shell configs if not already present
    MANPATH_LINE="export MANPATH=\"\$HOME/.local/share/man:\${MANPATH:-\$(manpath 2>/dev/null)}\"  # CW man pages"
    for RC_FILE in "$HOME/.bashrc" "$HOME/.zshrc"; do
        if [ -f "$RC_FILE" ] && ! grep -q "# CW man pages" "$RC_FILE" 2>/dev/null; then
            echo "$MANPATH_LINE" >> "$RC_FILE"
        fi
    done
    echo "  ✓ Man pages installed (after source ~/.bashrc: man cw, man cw-list, ...)"
else
    echo "  ⚠ help2man not found — skipping man pages"
    echo "    Install with: brew install help2man"
fi

# ─── Step 8: Shell completion ─────────────────────────────────────
# Install completion for ALL shells that have rc files present,
# since the user may run different shells in different iTerm profiles.
echo ""
echo "→ Step 8/9: Installing shell completion ..."

COMPLETION_INSTALLED=false

# Bash completion
BASHRC="$HOME/.bashrc"
if [ -f "$BASHRC" ]; then
    if grep -q "# CW bash completion" "$BASHRC" 2>/dev/null; then
        echo "  ✓ Bash completion already in $BASHRC"
    else
        echo "" >> "$BASHRC"
        echo "# CW bash completion (added by Contextual-Walker install)" >> "$BASHRC"
        echo 'eval "$(cw completion bash)"' >> "$BASHRC"
        echo "  ✓ Bash completion added to $BASHRC"
    fi
    COMPLETION_INSTALLED=true
fi

# Zsh completion
ZSHRC="$HOME/.zshrc"
if [ -f "$ZSHRC" ]; then
    if grep -q "# CW zsh completion" "$ZSHRC" 2>/dev/null; then
        echo "  ✓ Zsh completion already in $ZSHRC"
    else
        echo "" >> "$ZSHRC"
        echo "# CW zsh completion (added by Contextual-Walker install)" >> "$ZSHRC"
        echo 'eval "$(cw completion zsh)"' >> "$ZSHRC"
        echo "  ✓ Zsh completion added to $ZSHRC"
    fi
    COMPLETION_INSTALLED=true
fi

# Fish completion
FISH_DIR="$HOME/.config/fish/completions"
if [ -d "$HOME/.config/fish" ]; then
    mkdir -p "$FISH_DIR"
    cw completion fish > "$FISH_DIR/cw.fish"
    echo "  ✓ Fish completion installed at $FISH_DIR/cw.fish"
    COMPLETION_INSTALLED=true
fi

if [ "$COMPLETION_INSTALLED" = false ]; then
    echo "  ⚠ No shell config found — run manually:"
    echo "    cw completion bash >> ~/.bashrc"
    echo "    cw completion zsh  >> ~/.zshrc"
fi

# ─── Step 8: Configure backup directory ───────────────────────────
if [ -n "$CUSTOM_BACKUP_DIR" ]; then
    echo ""
    echo "→ Step 9/9: Configuring backup directory ..."
    cw config --backup-dir "$CUSTOM_BACKUP_DIR"
    echo "  ✓ Backup directory set to: $CUSTOM_BACKUP_DIR"
else
    echo ""
    echo "→ Step 9/9: Backup directory (default) ..."
    echo "  ✓ Using default: $CW_HOME/backups/"
    echo "    To change: cw config --backup-dir /your/path"
    echo "    Or reinstall: bash scripts/install.sh --backup-dir /your/path"
fi

# ─── Summary ──────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║              Installation complete!                      ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "What was installed:"
echo "  ✓ CW CLI        → cw (in .venv)"
echo "  ✓ Database       → $CW_HOME/cw.sqlite"
echo "  ✓ Daemon         → $DAEMON_WRAPPER"
if [ "$COMPLETION_INSTALLED" = true ]; then
echo "  ✓ Completion     → $USER_SHELL"
fi
echo ""
# Determine which rc file was modified
case "$USER_SHELL" in
    zsh)  RC_SOURCE="$HOME/.zshrc" ;;
    bash) RC_SOURCE="$HOME/.bashrc" ;;
    *)    RC_SOURCE="$HOME/.profile" ;;
esac

echo "To activate NOW (without opening a new tab), run:"
echo ""
echo "  source $RC_SOURCE"
echo ""
echo "Next steps:"
echo "  1. Restart iTerm2 (daemon will auto-start)"
echo "  2. (Optional) Show Context/Window name in iTerm panes:"
echo "     iTerm → Settings → Profiles → General → Badge:"
echo '       \(user.cw_context_name) / \(user.cw_window_name)'
echo ""
echo "Quick start:"
echo "  cw create MyProject     # Track current window"
echo "  cw list                 # See all contexts"
echo "  cw close MyProject      # Save & close"
echo "  cw open MyProject       # Restore"
